#!/usr/bin/env bash

##
## Usage: dock {build|run|exec}
##

DOCKER="docker"
EXEC_CMD="exec"
BUILD_CMD="build"
RUN_CMD="container run"
CONTAINER_NAME="fs"
IMAGE_NAME="fisop-fs"

usage() {
    echo "Usage: $0 {build|run|exec}"
    exit 1
}

build_container() {
    $DOCKER $BUILD_CMD -t "$IMAGE_NAME" -f Dockerfile .
}

run_container() {
    # Permitir acceso al servidor X del host
    xhost +local:docker

    # Ejecutar el contenedor con X11 forwarding
    $DOCKER $RUN_CMD -it --rm --name="$CONTAINER_NAME" \
        -v "$PWD":/fisopfs \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -e DISPLAY="$DISPLAY" \
        --device /dev/fuse \
        --cap-add SYS_ADMIN \
        --security-opt apparmor:unconfined \
        "$IMAGE_NAME" bash

    # Revocar acceso al servidor X cuando termine
    xhost -local:docker
}

exec_container() {
    $DOCKER $EXEC_CMD -it "$CONTAINER_NAME" bash
}

main() {
    case $1 in
        build)
            build_container
            ;;
        run)
            run_container
            ;;
        exec)
            exec_container
            ;;
        *)
            usage
            ;;
    esac
}

main $1
